FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy .env file
COPY .env ./

# Copy source code
COPY src ./src
COPY tsconfig.json ./

EXPOSE 8000

CMD ["npm", "run", "dev"]